server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
logging:
  level:
    com.leyou.userservice: debug
mybatis:
  type-aliases-package: com.leyou.com.leyou.userservice.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

